### ISSUE TITLE
Pleeeaase! how is the new maner to program FFmpeg v4.1.4 ?

### ISSUE THREAD

**Issue by danieagle** [leixiaohua1020/simplest_ffmpeg_device#2]
Hi!

I really love the example  "simplest_ffmpeg_readcamer.cpp" but I in trouble com 'Deprecate Warnings' while compiling the src code.

My main need is an universal grabe video from cams and webcams and "shot it" to a png/jpeg buffer. the buffer will itself in a gtk3 image widget and in a QRCode analizer.

Very Very Very Thanks In Advance!!

My System is an Linux Amd64 v19.10 Ubuntu.
in annex a file with the remaining errors.

[deprecate_warnings.txt](https://github.com/leixiaohua1020/simplest_ffmpeg_device/files/3612719/deprecate_warnings.txt)

**Comment by Maxwelllmj** [comment]
Thunder(leixiaohua) passed away three years ago when he was 26.  You can do it yourself,  His great soul will bless you.

**Comment by danieagle** [comment]
Well... Rest in Peace. 

God bless all.
